config/routes.rb
Ticketee::Application.routes.draw do

  root :to => "projects#index"

  namespace :admin do
    root :to => "base#index"
    resources :users
  end

  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  resources :users

  resources :projects do
    resources :tickets do
      collection do
        get :search
      end
    end
  end

  resources :tickets do
    resources :comments 
    resources :tags do
      member do
        delete :remove
      end
    end
      get 'download'
  end

  namespace :api do
    namespace :v1 do
      resources :projects, defaults: {format: :json} do
        resources :tickets
      end
    end
    namespace :v2 do
      resources :projects, defaults: {format: :json} do
        resources :tickets
      end
    end
  end

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true,length: { minimum: 10 }
  belongs_to :user
  belongs_to :project
  belongs_to :state
  has_many :assets
  accepts_nested_attributes_for :assets
  attr_accessor :tag_names
  has_many :comments
  has_and_belongs_to_many :tags
  before_create :associate_tags
  config = ActiveRecord::Base.configurations[::Rails.env]
  ActiveRecord::Base.establish_connection
  config["adapter"]

  searcher do
    label :tag, :from => :tags, :field => :name
  end

  private

  def associate_tags
    if tag_names
      tag_names.split(",").each do |name|
        self.tags << Tag.find_or_create_by_name(name)
      end
    end
  end
  scope :test,->(time){ where("id=?",time) }

  def self.test(time) 
    puts ActiveRecord::Base.connection.execute("Select * from tickets group by title ")
  end

 end

app/controllers/api/v1/tickets_controller.rb
class Api::V1::TicketsController < Api::BaseController
  before_filter :find_project

  def index
    respond_with(@project.tickets)
  end

  private

  def find_project
    @project = Project.find(params[:project_id])
    rescue ActiveRecord::RecordNotFound
      error = { :error => "The project you were looking for" +
      " could not be found."}
      respond_with(error, :status => 404)
  end
end

app/controllers/api/v2/tickets_controller.rb
class Api::V2::TicketsController < Api::BaseController
  before_filter :find_project

  def index
    respond_with(@project.tickets.page(params[:page]))
  end

  private

  def find_project
    @project = Project.find(params[:project_id])
    rescue ActiveRecord::RecordNotFound
    error = { :error => "The project you were looking for" +
              " could not be found."}
    respond_with(error, :status => 404)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :require_signin!, except: [:show, :index]
  before_action :set_project ,only: [:show, :edit, :update, :destroy]
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def new
    @ticket = @project.tickets.build
    3.times { @ticket.assets.build }
  end

  def show
    @comment = @ticket.comments.build
    @states = State.all
  end

  def create
    @ticket = @project.tickets.build(ticket_params)
    @ticket.user = current_user
    if @ticket.save
      flash[:notice] = "Ticket has been created."
      redirect_to [@project, @ticket]
    else
      flash[:alert] = "Ticket has not been created."
      render :action => "new"
    end
  end

  def search
    @tickets = @project.tickets.search("tag:#{params[:search]}")
    @project.tickets = @tickets.page(params[:page]).per(5)
    redirect_to [@project]
  end

  def download 
    url = Ticket.find(305).assets.first.asset.url 
    url_path = "#{Rails.root}/public#{url}"
    send_file url_path
  end


  private

  def ticket_params
    params.require(:ticket).permit(:title, :description,:tag_names,assets_attributes: [:asset])
  end

  def set_ticket
    @ticket = @project.tickets.find(params[:id])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

end

app/helpers/tickets_helper.rb
module TicketsHelper
  def state_for(comment)
    content_tag(:div, :class => "states") do
      if comment.state
        previous_state = comment.previous_state
        if previous_state && comment.state != previous_state
          "#{render previous_state} &rarr; #{render comment.state}"
        else
          render(comment.state)
        end
      end
    end
  end
end

app/views/tickets/_form.html.erb
<%= form_for [@project, @ticket], html: { multipart: true } do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %>
      prohibited this ticket from being saved:</h2>
      <ul>
        <% @ticket.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :tag_names %>
    <%= f.text_field :tag_names %>
  </p>
  <% number = 0 %>
  <%= f.fields_for :assets do |asset| %>
  <p>
    <%= asset.label :asset, "File ##{number += 1}" %>
    <%= asset.file_field :asset %>
  </p>
<% end %>
  <%= f.submit %>
<% end %>

app/views/tickets/new.html.erb
<h2>New Ticket</h2>
<%= render "form" %>

app/views/tickets/show.html.erb
<div id='ticket'>
  <h2><%= @ticket.title %></h2>
  <span id='author'></span>
    <%= simple_format(@ticket.description) %>
    <div id='tags'>
      <%= render @ticket.tags  %>
      <%if @ticket.tags %>
        <% render @ticket.tags.select(&:persisted?) %>   
      <% end %>
    </div>
    <% if @ticket.assets.present?  %>
      <h3>Attached Files</h3>
      <div class="assets">
      <% @ticket.assets.each do |asset| %>
        <p>
          <%= link_to File.basename(asset.asset.path),asset.asset.url %>
      <%= link_to 'Download', ticket_download_path(@ticket.id) %>
        </p>
        <p>
          <small><%= number_to_human_size(asset.asset.size) %> </small>
        </p>
      <% end %>

    </div>
  <% end %>
  <h3>Comments</h3>
    <div id='comments'>
      <% if @ticket.comments.exists? %> 
        <%= render @ticket.comments.select(&:persisted?) %>

      <% else %>
        There are no comments for this ticket.
      <% end %>
    </div>
    <%= render "comments/form" %>
</div>