config/routes.rb
Ticketee::Application.routes.draw do

  root :to => "projects#index"

  namespace :admin do
    root :to => "base#index"
    resources :users
  end

  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  resources :users

  resources :projects do
    resources :tickets do
      collection do
        get :search
      end
    end
  end

  resources :tickets do
    resources :comments 
    resources :tags do
      member do
        delete :remove
      end
    end
      get 'download'
  end

  namespace :api do
    namespace :v1 do
      resources :projects, defaults: {format: :json} do
        resources :tickets
      end
    end
    namespace :v2 do
      resources :projects, defaults: {format: :json} do
        resources :tickets
      end
    end
  end

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tickets
  belongs_to :user
  validates :name, presence: true

  def last_ticket
    tickets.last
  end
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < Api::BaseController
  before_filter :find_project, :only => [:show,:update,:destroy]

  def index
    respond_with(current_user.projects)
  end

  def show
    respond_with(@project, :methods => "last_ticket")
  end

  def create
    project = Project.new(params[:project])
    if project.save
      respond_with(project, :location => api_v1_project_path(project))
    else
      respond_with(project)
    end
  end

  def update
    @project.update_attributes(params[:project])
    respond_with(@project)
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end

  private
  def find_project
    @project = Project.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    error = { :error => "The project you were looking for " +
              "could not be found."}
    respond_with(error, :status => 404)
  end

end

app/controllers/api/v2/projects_controller.rb
class Api::V2::ProjectsController < Api::BaseController
  before_filter :find_project, :only => [:show,:update,:destroy]

  def index
    respond_with(current_user.projects)
  end

  def show
    respond_with(@project, :methods => "last_ticket")
  end

  def create
    project = Project.new(params[:project])
    if project.save
      respond_with(project, :location => api_v1_project_path(project))
    else
      respond_with(project)
    end
  end

  def update
    @project.update_attributes(params[:project])
    respond_with(@project)
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end

  private
  def find_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    error = { :error => "The project you were looking for " +
              "could not be found."}
    respond_with(error, :status => 404)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authorize_admin!, except: [:index, :show]
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  caches_action :show, :cache_path => (proc do 
    project_path(project_path(params[:id]) +"/#{current_user}/#{params[:page] || 1}")
  end)

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash[:alert] = "Project has not been created."
      render :action => "new"
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated."
      render action: "edit"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "Project has been destroyed."
    redirect_to projects_path
  end

  def show
    @tickets = @project.tickets
    @tickets = @tickets.page(params[:page]).per(50)
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def set_project
    @project = Project.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking" +
      " for could not be found."
    redirect_to projects_path
  end

  def authorize_admin!
    unless current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to root_path
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %>
        prohibited this project from being saved:</h2>
        <ul>
          <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
    <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit project</h2>
<%= render "form" %>

app/views/projects/index.html.erb
<h2>Projects</h2>
<ul>
  <% @projects.each do |project| %>
       <li><%= link_to project.name, project %></li>
  <% end %>
<% admins_only do %>
<%= link_to "New Project", new_project_path %>
<%end%>
</ul>

app/views/projects/new.html.erb
<%= render "form" %>

app/views/projects/show.html.erb
<ul id='tickets'>
  <%= paginate @tickets %>
  <% @tickets.each do |ticket| %>
    <li>
      <%= ticket.id %> 
      <%= link_to ticket.title, [@project, ticket] %>
    </li>
  <% end %>
      <%= link_to "New Ticket", new_project_ticket_path(@project) %>
</ul>