config/routes.rb
Ticketee::Application.routes.draw do

  root :to => "projects#index"

  namespace :admin do
    root :to => "base#index"
    resources :users
  end

  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  resources :users

  resources :projects do
    resources :tickets do
      collection do
        get :search
      end
    end
  end

  resources :tickets do
    resources :comments 
    resources :tags do
      member do
        delete :remove
      end
    end
      get 'download'
  end

  namespace :api do
    namespace :v1 do
      resources :projects, defaults: {format: :json} do
        resources :tickets
      end
    end
    namespace :v2 do
      resources :projects, defaults: {format: :json} do
        resources :tickets
      end
    end
  end

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :require_signin!, except: [:show, :index]

  def remove
    @ticket = Ticket.find(params[:ticket_id])
    if current_user.admin?
      @tag = Tag.find(params[:id])
      @ticket.tags -= [@tag]
      @ticket.save
      render :nothing => true
    end
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_tag.html.erb
<span class='tag'/>
<% if  current_user.admin? %>
  <%= link_to "x", remove_ticket_tag_path(@ticket, tag),:method => :delete,:remote => true,:id => "delete-#{tag.name.parameterize}" %> 
  <%= tag.name %>
  <%= link_to tag.name,
      search_project_tickets_path(@ticket.project,
      :search => "tag:#{tag.name}") %>
  <% end %>
</span>

app/views/tags/remove.js.erb
$('a#delete-<%= @tag.name.parameterize %>').parent().remove();